name: Deploy SAM Infra

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions

      - name: Install SAM CLI
        run: |
          sudo pip install aws-sam-cli

      - name: Build SAM
        run: |
          sam build --template-file infra/sam-template.yaml

      - name: Deploy SAM
        env:
          STACK_NAME: growksh-infra
        run: |
          sam deploy --template-file .aws-sam/build/template.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset
